export {
	REGISTER_START,
	REGISTER_SUCCESS,
	REGISTER_FAILURE,
	//
	LOGIN_START,
	LOGIN_SUCCESS,
	LOGIN_FAILURE,
	//
	GET_ALL_USERS_START,
	GET_ALL_USERS_SUCCESS,
	GET_ALL_USERS_FAILURE,
	//
	GET_USER_BY_ID_START,
	GET_USER_BY_ID_SUCCESS,
	GET_USER_BY_ID_FAILURE,
	//
	GET_USER_INFO_START,
	GET_USER_INFO_SUCCESS,
	GET_USER_INFO_FAILURE,
	//
	UPDATE_USER_START,
	UPDATE_USER_SUCCESS,
	UPDATE_USER_FAILURE,
	//
	DELETE_USER_START,
	DELETE_USER_SUCCESS,
	DELETE_USER_FAILURE,
} from './_users';

export {
	GET_ALL_SCHOOLS_START,
	GET_ALL_SCHOOLS_SUCCESS,
	GET_ALL_SCHOOLS_FAILURE,
	//
	GET_SCHOOL_BY_ID_START,
	GET_SCHOOL_BY_ID_SUCCESS,
	GET_SCHOOL_BY_ID_FAILURE,
	//
	GET_SCHOOLS_BY_USER_ID_START,
	GET_SCHOOLS_BY_USER_ID_SUCCESS,
	GET_SCHOOLS_BY_USER_ID_FAILURE,
	//
	ADD_SCHOOL_START,
	ADD_SCHOOL_SUCCESS,
	ADD_SCHOOL_FAILURE,
	///
	UPDATE_SCHOOL_START,
	UPDATE_SCHOOL_SUCCESS,
	UPDATE_SCHOOL_FAILURE,
	//
	DELETE_SCHOOL_START,
	DELETE_SCHOOL_SUCCESS,
	DELETE_SCHOOL_FAILURE,
} from './_schools';
